In [1]:
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "arro3-core",
#     "arro3-io",
#     "polars",
#     "scikit-learn",
#     "umap-learn",
# ]
# ///

In [2]:
from arro3.io import read_parquet
import polars as pl

df = pl.from_arrow(read_parquet("../data/mair-2022-tumor-006-ozette.pq"))
df.head(10)

shape: (10, 39)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ umapX     ┆ umapY     ┆ faustLabe ┆ CD4_Winds ┆ … ┆ TCRgd_fau ┆ CD38_faus ┆ CD127_fau ┆ Tim3_fau │
│ ---       ┆ ---       ┆ ls        ┆ orized    ┆   ┆ st_annota ┆ t_annotat ┆ st_annota ┆ st_annot │
│ f64       ┆ f64       ┆ ---       ┆ ---       ┆   ┆ tion      ┆ ion       ┆ tion      ┆ ation    │
│           ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ -12.19795 ┆ 10.958616 ┆ CD4+CD8-C ┆ 0.895259  ┆ … ┆ -         ┆ -         ┆ +         ┆ -        │
│ 9         ┆           ┆ D3+CD45RA ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ -CD27+CD1 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 9-C…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ -0.338861 ┆ -4.746182 ┆ CD4-CD8+C ┆ 0.16023   ┆ … ┆ -         ┆ -         ┆ -         ┆ -        │
│           ┆           ┆ D3+CD45RA ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ -CD27+CD1 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 9-C…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ -6.862342 ┆ -14.07071 ┆ CD4-CD8+C ┆ 0.130605  ┆ … ┆ -         ┆ +         ┆ -         ┆ -        │
│           ┆           ┆ D3+CD45RA ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ -CD27+CD1 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 9-C…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ -9.874931 ┆ 0.273441  ┆ 0_0_0_0_0 ┆ 0.77299   ┆ … ┆ -         ┆ -         ┆ -         ┆ +        │
│ 7.248039  ┆ 4.996465  ┆ CD4-CD8-C ┆ 0.16673   ┆ … ┆ -         ┆ -         ┆ -         ┆ -        │
│           ┆           ┆ D3-CD45RA ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ +CD27-CD1 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 9+C…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ -0.513573 ┆ -0.9577   ┆ CD4-CD8+C ┆ 0.079497  ┆ … ┆ -         ┆ -         ┆ +         ┆ -        │
│           ┆           ┆ D3+CD45RA ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ -CD27-CD1 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 9-C…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ -1.749071 ┆ -6.924024 ┆ CD4-CD8+C ┆ 0.031539  ┆ … ┆ -         ┆ -         ┆ -         ┆ -        │
│           ┆           ┆ D3+CD45RA ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ -CD27+CD1 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 9-C…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ -4.607378 ┆ -11.69912 ┆ CD4-CD8+C ┆ 0.251677  ┆ … ┆ -         ┆ -         ┆ -         ┆ -        │
│           ┆           ┆ D3+CD45RA ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ -CD27+CD1 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 9-C…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1.178266  ┆ -7.828167 ┆ 0_0_0_0_0 ┆ 0.09876   ┆ … ┆ -         ┆ -         ┆ -         ┆ -        │
│ -0.98767  ┆ -13.83850 ┆ CD4-CD8+C ┆ 0.038986  ┆ … ┆ -         ┆ +         ┆ -         ┆ -        │
│           ┆ 5         ┆ D3+CD45RA ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ -CD27+CD1 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 9-C…      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
cols = [col for col in df.columns if col.endswith("Windsorized")]
cols

['CD4_Windsorized',
 'CD8_Windsorized',
 'CD3_Windsorized',
 'CD45RA_Windsorized',
 'CD27_Windsorized',
 'CD19_Windsorized',
 'CD103_Windsorized',
 'CD28_Windsorized',
 'CD69_Windsorized',
 'PD1_Windsorized',
 'HLADR_Windsorized',
 'GranzymeB_Windsorized',
 'CD25_Windsorized',
 'ICOS_Windsorized',
 'TCRgd_Windsorized',
 'CD38_Windsorized',
 'CD127_Windsorized',
 'Tim3_Windsorized']

In [5]:
from sklearn.preprocessing import StandardScaler

scaled_df = StandardScaler().fit_transform(df.select(cols).to_numpy())

In [9]:
from umap import UMAP

umap = UMAP(n_components=4)
embedding = umap.fit_transform(scaled_df)

In [10]:
result = pl.DataFrame(
    {f"umap_{i}": embedding[:, i] for i in range(embedding.shape[1])}
).with_columns(df.get_column("faustLabels").alias("label"))

result.write_parquet("../data/mair-2022-tumor-006-ozette-umap-4d.pq")

In [11]:
result.head(10)

shape: (10, 5)
┌───────────┬───────────┬───────────┬───────────┬─────────────────────────────────┐
│ umap_0    ┆ umap_1    ┆ umap_2    ┆ umap_3    ┆ label                           │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---                             │
│ f32       ┆ f32       ┆ f32       ┆ f32       ┆ str                             │
╞═══════════╪═══════════╪═══════════╪═══════════╪═════════════════════════════════╡
│ 10.715034 ┆ -1.335521 ┆ 0.867442  ┆ 8.945329  ┆ CD4+CD8-CD3+CD45RA-CD27+CD19-C… │
│ 10.564323 ┆ 10.607113 ┆ 0.532181  ┆ 11.21756  ┆ CD4-CD8+CD3+CD45RA-CD27+CD19-C… │
│ 11.062168 ┆ 11.656316 ┆ -0.469385 ┆ 6.795445  ┆ CD4-CD8+CD3+CD45RA-CD27+CD19-C… │
│ 9.866688  ┆ -1.102489 ┆ 0.601316  ┆ 5.879847  ┆ 0_0_0_0_0                       │
│ -0.663751 ┆ 5.684612  ┆ -1.597874 ┆ 7.762625  ┆ CD4-CD8-CD3-CD45RA+CD27-CD19+C… │
│ 12.393549 ┆ 9.704292  ┆ 1.10407   ┆ 9.705588  ┆ CD4-CD8+CD3+CD45RA-CD27-CD19-C… │
│ 11.798922 ┆ 9.653658  ┆ 0.21165   ┆ 10.116335 ┆ CD4-CD8+CD3+CD45RA-CD27+CD19-C… │
│ 10.236522 ┆ 11.53494  ┆ 0.561314  ┆ 7.284149  ┆ CD4-CD8+CD3+CD45RA-CD27+CD19-C… │
│ 11.172862 ┆ 9.770474  ┆ 0.541621  ┆ 10.400032 ┆ 0_0_0_0_0                       │
│ 9.682938  ┆ 10.626325 ┆ -0.690685 ┆ 12.070459 ┆ CD4-CD8+CD3+CD45RA-CD27+CD19-C… │
└───────────┴───────────┴───────────┴───────────┴─────────────────────────────────┘